import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Toaster } from "react-hot-toast";
import { toastConfig } from "@/config/config";
import { Chatbot } from "@/components/common/Chatbot";

export const metadata: Metadata = {
  title: "Kifiya DFC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className="antialiased max-w-screen w-full overflow-x-hidden min-h-screen">
        <ReactQueryProvider>
          {children}
          <Chatbot />
          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={toastConfig}
          />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
