import type { Metadata } from "next";
import "../globals.css";
export const metadata: Metadata = {
  title: "Kifya DFC",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
