import type { Metadata } from "next";
//import { Montserrat, Prompt } from "next/font/google";
import "../../globals.css";
import Navbar from "@/components/ui/header/NaveBar";
import Footer from "@/components/footer";
// import Navbar from "@/components/ui/header/NaveBar";
// import Footer from "@/components/footer";

// const geistSans = Montserrat({
//   variable: "--font-montserrat",
//   subsets: ["latin"],
// });

// const geistMono = Prompt({
//   variable: "--font-prompt",
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });

export const metadata: Metadata = {
  title: "Kifiya DFC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}
