import type { Metadata } from "next";
//import { Montserrat, Prompt } from "next/font/google";

import Navbar from "@/components/ui/header/NaveBar";

export const metadata: Metadata = {
  title: "Kifiya DFC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
      {/* <Footer /> */}
    </>
  );
}
